### GET request to example server
## name, email, password, registered_at
POST http://localhost:8080/users
Content-Type: application/json
x-id: 1

{
  "name": "user100",
  "email": "user100@test.com",
  "password": "123456"
}